/*
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractChartDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.tad.chart.xtext.chartDsl.ChartDslPackage.eINSTANCE);
		return result;
	}
	
}
