/*
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ChartDslStandaloneSetup extends ChartDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ChartDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
