/*
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.serializer;

import com.google.inject.Inject;
import com.tad.chart.xtext.chartDsl.ChartDslPackage;
import com.tad.chart.xtext.chartDsl.Company;
import com.tad.chart.xtext.chartDsl.Employee;
import com.tad.chart.xtext.chartDsl.Project;
import com.tad.chart.xtext.chartDsl.Task;
import com.tad.chart.xtext.services.ChartDslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ChartDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ChartDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ChartDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ChartDslPackage.COMPANY:
				sequence_Company(context, (Company) semanticObject); 
				return; 
			case ChartDslPackage.EMPLOYEE:
				sequence_Employee(context, (Employee) semanticObject); 
				return; 
			case ChartDslPackage.PROJECT:
				sequence_Project(context, (Project) semanticObject); 
				return; 
			case ChartDslPackage.TASK:
				sequence_Task(context, (Task) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Company returns Company
	 *
	 * Constraint:
	 *     (name=ID employees+=Employee* projects+=Project*)
	 */
	protected void sequence_Company(ISerializationContext context, Company semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Employee returns Employee
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Employee(ISerializationContext context, Employee semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ChartDslPackage.Literals.EMPLOYEE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ChartDslPackage.Literals.EMPLOYEE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEmployeeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Project returns Project
	 *
	 * Constraint:
	 *     (name=ID projectType=ProjectType tasks+=Task*)
	 */
	protected void sequence_Project(ISerializationContext context, Project semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Task returns Task
	 *
	 * Constraint:
	 *     (name=ID responsable=[Employee|ID])
	 */
	protected void sequence_Task(ISerializationContext context, Task semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ChartDslPackage.Literals.TASK__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ChartDslPackage.Literals.TASK__NAME));
			if (transientValues.isValueTransient(semanticObject, ChartDslPackage.Literals.TASK__RESPONSABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ChartDslPackage.Literals.TASK__RESPONSABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTaskAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTaskAccess().getResponsableEmployeeIDTerminalRuleCall_3_0_1(), semanticObject.getResponsable());
		feeder.finish();
	}
	
	
}
