/*
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChartDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/tad/chart/xtext/parser/antlr/internal/InternalChartDsl.tokens");
	}
}
