/*
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractChartDslScopeProvider extends DelegatingScopeProvider {
}
