/**
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.chartDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Company#getName <em>Name</em>}</li>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Company#getEmployees <em>Employees</em>}</li>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Company#getProjects <em>Projects</em>}</li>
 * </ul>
 *
 * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getCompany()
 * @model
 * @generated
 */
public interface Company extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getCompany_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.tad.chart.xtext.chartDsl.Company#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference list.
   * The list contents are of type {@link com.tad.chart.xtext.chartDsl.Employee}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Employees</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference list.
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getCompany_Employees()
   * @model containment="true"
   * @generated
   */
  EList<Employee> getEmployees();

  /**
   * Returns the value of the '<em><b>Projects</b></em>' containment reference list.
   * The list contents are of type {@link com.tad.chart.xtext.chartDsl.Project}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projects</em>' containment reference list.
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getCompany_Projects()
   * @model containment="true"
   * @generated
   */
  EList<Project> getProjects();

} // Company
