/**
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.chartDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Project#getName <em>Name</em>}</li>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Project#getProjectType <em>Project Type</em>}</li>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Project#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getProject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.tad.chart.xtext.chartDsl.Project#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Project Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.tad.chart.xtext.chartDsl.ProjectType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Type</em>' attribute.
   * @see com.tad.chart.xtext.chartDsl.ProjectType
   * @see #setProjectType(ProjectType)
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getProject_ProjectType()
   * @model
   * @generated
   */
  ProjectType getProjectType();

  /**
   * Sets the value of the '{@link com.tad.chart.xtext.chartDsl.Project#getProjectType <em>Project Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project Type</em>' attribute.
   * @see com.tad.chart.xtext.chartDsl.ProjectType
   * @see #getProjectType()
   * @generated
   */
  void setProjectType(ProjectType value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link com.tad.chart.xtext.chartDsl.Task}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getProject_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // Project
