/**
 * generated by Xtext 2.9.2
 */
package com.tad.chart.xtext.chartDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Task#getName <em>Name</em>}</li>
 *   <li>{@link com.tad.chart.xtext.chartDsl.Task#getResponsable <em>Responsable</em>}</li>
 * </ul>
 *
 * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getTask_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.tad.chart.xtext.chartDsl.Task#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Responsable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Responsable</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Responsable</em>' reference.
   * @see #setResponsable(Employee)
   * @see com.tad.chart.xtext.chartDsl.ChartDslPackage#getTask_Responsable()
   * @model
   * @generated
   */
  Employee getResponsable();

  /**
   * Sets the value of the '{@link com.tad.chart.xtext.chartDsl.Task#getResponsable <em>Responsable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Responsable</em>' reference.
   * @see #getResponsable()
   * @generated
   */
  void setResponsable(Employee value);

} // Task
